version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      # Генерация для auth service (sso.proto)
      - protoc -I . -I proto proto/sso/sso.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative --validate_out=lang=go:./gen/go --validate_opt=paths=source_relative

      # Генерация для chat service (sso.proto)
      - protoc -I . -I proto proto/chat/chat.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
